import { STATE } from "../state";

export async function finalizeNode(state:STATE):Promise<STATE>{
  const query = state.query;
  const userID = state.userID;
  const docID = state.docID;
  const contexts = state.contexts;
  let answer = state.answer
  const chunkIDs = state.chunkIDs ?? []
  let message = state.message ?? ""

  if(!contexts || contexts.length === 0){
    answer = "No relevant context found, hence no answer generated."
    message = "No relevant context was fetched. Issue at retireverNode"
  }
  if(contexts && contexts.length > 0 && !answer){
    answer = "Due to some techincal issue no answer was generated."
    message = "Now asnwer was generated by the model. Issue at queryModelNode"
  }
  return {
    query,
    userID,
    docID,
    contexts,
    answer,
    chunkIDs,
    message
  }
}